[env:esp32dev]
platform = platformio/espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
    -I include

; lib_deps =
;     adafruit/Adafruit BMP280 Library
;     sensirion/Sensirion I2C SHT4x
;     knolleary/PubSubClient

[env:native]
platform = native
test_framework = doctest
build_flags =
    -std=gnu++20
    -I include
